#!/bin/bash

# Drop a commit, similar to the drop directive in 'git rebase -i'
# Based on https://stackoverflow.com/a/52324605/10210798 (CC BY-SA 4.0)

set -euo pipefail

script_name=${0##*/}

warn() {
    >&2 printf '%s: %s\n' "$script_name" "$*"
}
die() {
    warn "$@"
    exit 1
}

case $# in
    0) ref=HEAD ;;
    1) ref="$1" ;;
    *) die "Expected single commit to drop." ;;
esac

commit=$(git rev-parse --short "$ref")
message=$(git log -1 --format='%h %s' "$commit")

if [[ $OSTYPE =~ ^darwin ]]; then
    sed_inplace=(sed -Ei "")
else
    sed_inplace=(sed -Ei)
fi

export GIT_SEQUENCE_EDITOR="${sed_inplace[*]} "' "s/^pick ('"$commit"' .*)/drop \\1/"'
git rebase --quiet --interactive --autostash --autosquash "$commit"~
printf "Dropped commit: %s\n" "$message"
