{
 "title": "Bumblebee Desktops Running",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total desktops running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (bumblebee_desktops_running_total{})",
     "legendFormat": "Desktops"
    }
   ]
  },
  {
   "title": "Desktops running by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (type) (bumblebee_desktops_running_by_type{})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Desktops by zone",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (zone) (bumblebee_desktops_running_by_zone{})",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Desktops by domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (domain) (bumblebee_desktops_running_by_domain{})",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}